### PR TITLE
Debug image handling

### PR DESCRIPTION
**Pull request by juergmessmer**
I included both

- description added as argument for better information on the image resource that can't be created
- and the fix in case the resource is not rewound
in this branch.
Maybe we can just cherry-pick the fix in older releases?

### CODE REVIEW

**Comment by juergmessmer** [comment]
> @sabberworm approved this pull request.
> 
> Looks good to me. But, as I said, make sure we can merge it to at least 1.7 (better 1.5).
> 
I checked in your suggested improvements.
Now about merging: how do I do this best?

Checkout release-1.5 and merge the branch Debug image handling and then merge 1.5 into 1.6 and then merge it finally into master?

**Comment by sabberworm** [comment]
> Now about merging: how do I do this best? Checkout release-1.5 and merge the branch Debug image handling and then merge 1.5 into 1.6 and then merge it finally into master?

Since the branch is based on master, that will merge all of master into 1.5. So you need to rebase first:

    git rebase --onto release-1.6 master debug_image_handling

**Comment by juergmessmer** [comment]
> On 7 Oct 2018, at 14:44, Raphael Schweikert <notifications@github.com> wrote:
> git rebase --onto release-1.6 master debug_image_handling

I guess you mean release-1.5 here?

So that I understand everything clearly: 
"git rebase —onto” - the way you suggest it - does “connect” the “debug_image_handling” branch to release-1.5 instead of master?

Does this rebase action automatically merge or is this still required:
 “checkout release-1.5” and  "merge debug_image_handling”

and then 
"checkout release-1.7” and "merge release-1.5”

and finally
"checkout master” and "merge release-1.7”

Thank you for clarifying this procedure since git manuals always leave me confused...

**Comment by sabberworm** [comment]
No idea why travis fails. I’m merging now.

**Comment by juergmessmer** [comment]
Danke, kann ich jetzt 1.5 ins 1.7 und dann in master mergen?
 (morgen)

**Pull request merged**
